version: '3'

services:
  message-service:
    build: .
    container_name: message-service
    image: the-message
    ports:
      - "8080:8080"
    
  redis:
    container_name: my-redis
    image: redis:latest
    ports:
      - "6379:6379"