version: "3.5"

services:
    message-services:
        image: "golang:1.17-alpine"
        volumes:
            - '../Backend:/app'
        ports:
            - "8080:8080"
        working_dir: '/app'
        tty: true
        command: "go run main.go"