name: 🎯 Backend Acceptance Test

on:
  pull_request:
    types:
      - closed

env:
  GO_VERSION: 1.21

jobs:
  acceptance_test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}


      - name: Migration
        working-directory: ./Backend
        run: go run ./cmd/migrate/migrate.go
      - name: Acceptance test
        working-directory: ./Backend
        run: go test ./... -v -count=1 -coverprofile=coverage.out

      - name: Upload acceptance test coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: acceptance-test-coverage-report
          path: ./Backend/coverage.out