name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Change the location
        run: cd Backend

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
