name: Backend CI

on:
  push:
    paths:
      - Backend/**
      - .github/workflows/test-go-unit.yml
  pull_request_target:
    paths:
      - Backend/**
      - .github/workflows/test-go-unit.yml

jobs:
  build:

    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.1.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: test
          MYSQL_USER: user
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - "3306:3306"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Env handle
        working-directory: ./Backend
        run: cp env .env

      - name: Build
        working-directory: ./Backend
        run: go build -v ./...

      - name: Migration
        working-directory: ./Backend
        run: go run ./cmd/migrate/migrate.go

      - name: Test
        working-directory: ./Backend
        run: go test ./... -v -count=1 -coverprofile=coverage.out

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./Backend/coverage.out
